# Generated by Django 5.2.14 on 2026-06-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventmodule_description_eventmodule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodule',
            name='form_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ModuleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='events.eventmodule')),
            ],
        ),
    ]
