# Generated by Django 5.2.14 on 2026-06-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventmodule_form_schema_moduleentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('days_before_event', models.IntegerField()),
                ('due_date', models.DateField()),
                ('assigned_role', models.CharField(default='Organizer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='events.event')),
            ],
        ),
    ]
