# Generated by Django 5.2.14 on 2026-06-09 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventtimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='eventtask',
            name='priority',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_level', models.CharField(max_length=50)),
                ('ai_recommendation', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_summary', to='events.event')),
            ],
        ),
    ]
