# Generated by Django 5.2.14 on 2026-06-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_budget_alter_event_prize_money_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('Description', 'Description'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('WhatsApp', 'WhatsApp'), ('SponsorPitch', 'SponsorPitch'), ('PressRelease', 'PressRelease'), ('Hashtags', 'Hashtags')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_contents', to='events.event')),
            ],
        ),
    ]
