# Generated by Django 5.2.14 on 2026-06-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventtask_description_eventtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcontent',
            name='content_type',
            field=models.CharField(choices=[('Description', 'Description'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('WhatsApp', 'WhatsApp'), ('LinkedIn', 'LinkedIn'), ('EmailCampaign', 'EmailCampaign'), ('SponsorPitch', 'SponsorPitch'), ('PressRelease', 'PressRelease'), ('VolunteerRecruitment', 'VolunteerRecruitment'), ('Hashtags', 'Hashtags')], max_length=50),
        ),
    ]
