# Generated by Django 5.2.14 on 2026-06-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_marketingcontent_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtimeline',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtimeline',
            name='related_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_items', to='events.eventmodule'),
        ),
    ]
