# Generated by Django 5.2.14 on 2026-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventtimeline_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodule',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventtimeline',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
