# Generated by Django 5.2.14 on 2026-06-09 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(max_length=100)),
                ('risk_level', models.CharField(max_length=50)),
                ('volunteers_required', models.CharField(max_length=255)),
                ('security_required', models.CharField(max_length=255)),
                ('raw_ai_response', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='events.event')),
            ],
        ),
    ]
