# Generated by Django 5.2.14 on 2026-06-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='analytics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='risk_intelligence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='team_planning',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
